#ifndef ROSBRIDGE2CPP_GLOBAL_H
#define ROSBRIDGE2CPP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROSBRIDGE2CPP_LIBRARY)
#  define ROSBRIDGE2CPP_EXPORT Q_DECL_EXPORT
#else
#  define ROSBRIDGE2CPP_EXPORT Q_DECL_IMPORT
#endif

#endif // ROSBRIDGE2CPP_GLOBAL_H
